### ISSUE TITLE
numi Startup Problems

### ISSUE THREAD

**Issue by greenchapter** [nikolaeu/NumiKit#2]
The Dock Icon of numi **doesn't bounce** and the application itself **starts slow**.

<img width="244" alt="bildschirmfoto 2015-12-26 um 21 57 46" src="https://cloud.githubusercontent.com/assets/693276/12007915/c31b7d40-ac1b-11e5-80dc-dbcdc0a9893a.png">

**Comment by nikolaeu** [comment]
Since Numi might works from menubar, "application is agent" property is required. Seems it forced app to not "bounce" on start for dock mode.
