### ISSUE TITLE
Insecure update error from Sparkle

### ISSUE THREAD

**Issue by thibmaek** [nikolaeu/NumiKit#23]
I didn't find any other repo on Github regarding Numi.

<img width="532" alt="screen shot 2016-09-06 at 12 58 16" src="https://cloud.githubusercontent.com/assets/6213695/18271283/9d3271c2-7431-11e6-924c-1475bd0ded58.png">

**Comment by nikolaeu** [comment]
Thank you for report! What's the current version number do you have? I've tested previous build update: looks all good so far.

**Comment by thibmaek** [comment]
Current version is 3.0b13 installed with homebrew-cask (with --caskroom=/usr/local/Caskroom)

**Comment by thibmaek** [comment]
Closing since error doesn't occur anymore.
