### ISSUE TITLE
Rounding and precision

### ISSUE THREAD

**Issue by lgomez** [nikolaeu/NumiKit#24]
Hi,

Thank you for all the great work. Quick question: is there a way to specify precision when rounding? I'm adding up bitcoins with a precision of 8 but it's carrying that over after converting to US dollars where I'd like to display with a precision of 2.

Thank you

**Comment by lgomez** [comment]
Just in case... If there's a more appropriate medium for posting questions like this one, please let me know and I'll happily move it.

**Comment by nikolaeu** [comment]
Hey @lgomez,
You can specify precision in settings, but this will affect all computations. Will think about your case.

**Comment by lgomez** [comment]
Thank you!
