### ISSUE TITLE
Confused with Steps

### ISSUE THREAD

**Issue by SethCalkins** [nikolaeu/NumiKit#26]
I apologize, I'm new with Xcode, and in the process of learning... I'm stuck on this step, and I don't understand this step. How do I add `a main plugin class?`

> 
> 4. Add main plugin class, it should derive from `NumiPlugin` and contains setup function:
> 
> ```swift
> import Numi
> 
> class SampleNumiPlugin : NumiPlugin {
>   override func setup(module: Numi) {
>     NSLog("Plugin loaded")
>     // put your plugin code here
>   }
> }
> ```

**Comment by nikolaeu** [comment]
`File -> New -> Swift` I think with name of your class.
