### ISSUE TITLE
Invalid Character on calculation should not be considered

### ISSUE THREAD

**Issue by iGallina** [nikolaeu/NumiKit#3]
### Found a Bug:
if I type 3 and shift + 8 (4x) then  3 again:
3 * 3 * 3 * 3 * 3 = 243
if I type 3 and shift + 6 and spacebar and 5:
3^5 = 243
If I type 3 and shift + 6 and 5:
3ˆ5  = 8
If I type 3 and shift + = and 5:
3+5 = 8

ps. Made with Numi

**Comment by nikolaeu** [comment]
Fixed in beta 11
