### ISSUE TITLE
Running on OSx 10.10.5 ?

### ISSUE THREAD

**Issue by Aki92** [nikolaeu/NumiKit#32]
I tried Numi using Setapp and it was working perfectly fine on osX 10.10.5, but when I tried using the Beta version I can't use it.

Please help me in using it on osX 10.10.5.

**Comment by nikolaeu** [comment]
Here is the link for the Numi beta 13 with 10.10 support: https://dl.devmate.com/com.dmitrynikolaev.numi/80/1466339886/Numi-80.zip

**Comment by Aki92** [comment]
Thanks a lot @nikolaeu for building such a nice tool 👍 . Love it a lott...
