### ISSUE TITLE
Numi's factorials not working

### ISSUE THREAD

**Issue by Klemart3D** [nikolaeu/NumiKit#4]
Numi is beautiful but factorial function seems not working (?!) :

![numis-screen](https://cloud.githubusercontent.com/assets/7419525/12235595/08749a42-b875-11e5-942f-de5835316372.jpg)

**Comment by 601186678** [comment]
@Klemart3D  
use like 
```
fact 10 = 3,628,800
```

**Comment by se77en** [comment]
@Klemart3D use fact function like this:
```
fact 10
```

**Comment by Klemart3D** [comment]
I was only apply documentation ;)

![numi-fact-function](https://cloud.githubusercontent.com/assets/7419525/12548903/d6773cc6-c359-11e5-9c5a-3e6b90f64848.jpg)

**Comment by nikolaeu** [comment]
Yep @se77en right, `fact` should be used right now. Documentation will be fixed soon (beta 11 is coming).

**Comment by nikolaeu** [comment]
Documentation updated
