### ISSUE TITLE
Scientific notation, negative exponent not working

### ISSUE THREAD

**Issue by henrymuppet** [nikolaeu/NumiKit#5]
Hi,

Thanks for numi. It is awesome.

Perhaps I am doing something wrong, but when I use scientific notation, Numi does not recognize negative exponents.

Working:
1e6 displays 1,000,000
1e-6 displays nothing
1e(-6) displays nothing

I am running beta 10.

**Comment by nikolaeu** [comment]
Hey @henrymuppet,

Thank you for the bug! Fixed in upcoming version:
http://numi.io/static/dev/Numi.zip
