### ISSUE TITLE
Numi.framework contains no headers

### ISSUE THREAD

**Issue by yogipatel** [nikolaeu/NumiKit#7]
Thanks for fixing #6, but now it appears the framework is unusable since it does not contain any headers :)

**Comment by nikolaeu** [comment]
Hey @yogipatel 
Sorry for the delay man. Few changes are coming to framework that might affect how things will work, will fix ASAP.

**Comment by LukeeeeBennett** [comment]
Is this the cause of `No such module 'Numi'`?

**Comment by LukeeeeBennett** [comment]
Any updates? 😢 Dying to extend Numi.

**Comment by nikolaeu** [comment]
Sorry for the delay @LukeeeeBennett :(
Was on new build for the users. Will get to this ticket shortly!

**Comment by LukeeeeBennett** [comment]
@nikolaeu Not a problem, now I know! 💃

**Comment by nikolaeu** [comment]
Finally Fixed! Readme section and release sections updated as well.
